version = 0.1

[default.deploy.parameters]
stack_name = "shining-smiles-webhook-stack"
resolve_s3 = true
s3_prefix = "shining-smiles-webhook-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DeploymentVersion=\"2\" DatabaseUrl=\"postgresql://postgres:%23Alexander94@shining-smiles-db.cxu2ww2uu37o.us-east-2.rds.amazonaws.com:5432/shining_smiles?sslmode=require\" VerifyToken=\"shiningsmiles_verify_2025\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
